- hosts: all
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
    when: ansible_os_family == 'RedHat'

  - name: install Apache 
    package:
      name: "{{ package_name }}"
      state: latest

  - name: Make sure a service is running
    systemd:
      state: started
      enabled: yes
      name: "{{ service_name }}"

  - name: Download
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page291/gravita.zip
      dest: /tmp/construction.zip]

  - name: Install Unzip
    package:
      name: unzip
      state: latest

  - name: Extract a template
    unarchive:
      src: /tmp/construction.zip
      dest: /tmp/
      remote_src: yes

  - name: Move template files to /var/www/html 
    shell: "mv /tmp/html/* /var/www/html"
    args:
      creates: /var/www/html/contact.html

